### ISSUE TITLE
example usage

### ISSUE THREAD

**Issue by doctor** [gtramontina/elysia-tailwind#14]
Hello, do you have an example Elysia app using your plugin I can reference to? Thanks!

**Comment by gtramontina** [comment]
Hey there,
Apologies for the delay. The only app I have using this is closed, unfortunately. Though the usage [here](https://github.com/gtramontina/elysia-tailwind?tab=readme-ov-file#usage) should be enough to get you started. Please let me know if you face any issues.

**Comment by gtramontina** [comment]
Closing. Please re-open if the explanation above isn't clear. Cheers.

**Comment by dector** [comment]
@gtramontina 

I guess it would be nice to have some tiny example project for demo purposes.
For now documentation for this package is super-minimalistic and it's not clear how to use it. :)
